import { motion, AnimatePresence } from 'framer-motion';

const PRIORITY_STYLES = {
    HIGH: { bg: '#0A0A0A', color: '#FFFFFF', border: 'transparent' },
    MEDIUM: { bg: '#F3F4F6', color: '#374151', border: '#E5E7EB' },
    LOW: { bg: '#FFFFFF', color: '#9CA3AF', border: '#E5E7EB', dashed: true },
};

export default function RecoveryPlan({ actions, loading, onGenerate }) {
    return (
        <div className="bg-white rounded-xl border border-[#E5E7EB]" style={{ boxShadow: '0 1px 3px rgba(0,0,0,0.06)' }}>
            {/* Header */}
            <div className="px-6 pt-5 pb-3 border-b border-[#F3F4F6]">
                <p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#9CA3AF]">AI Recovery Plan</p>
                <p className="text-[11px] text-[#9CA3AF] mt-0.5">Generated by Gemini 1.5 Flash</p>
            </div>

            <div className="p-5">
                {/* Empty — generate button */}
                {!actions && !loading && (
                    <motion.button
                        whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.98, y: 1 }}
                        onClick={onGenerate}
                        className="w-full py-3 bg-[#0A0A0A] text-white rounded-xl flex items-center justify-center gap-2"
                        style={{ fontSize: 14, fontWeight: 700 }}>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                            <path d="M7 1v12M1 7h12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                        </svg>
                        Generate 72-Hour Recovery Plan
                    </motion.button>
                )}

                {/* Loading skeleton */}
                {loading && (
                    <div className="space-y-3">
                        <p className="text-[12px] text-[#9CA3AF] text-center mb-3">Generating via Gemini 1.5 Flash…</p>
                        {[1, 2, 3, 4, 5].map(i => (
                            <div key={i} className="h-14 skeleton-shimmer rounded-xl" style={{ animationDelay: `${i * 80}ms` }} />
                        ))}
                    </div>
                )}

                {/* Action cards */}
                <AnimatePresence>
                    {actions && (
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-3">
                            {actions.map((action, i) => {
                                const s = PRIORITY_STYLES[action.priority] || PRIORITY_STYLES.LOW;
                                return (
                                    <motion.div key={i}
                                        initial={{ opacity: 0, y: 6 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ type: 'spring', stiffness: 100, damping: 20, delay: i * 0.07 }}
                                        whileHover={{ y: -1, boxShadow: '0 4px 12px rgba(0,0,0,0.08)' }}
                                        className="border rounded-xl p-4 transition-shadow"
                                        style={{ borderColor: s.border, borderStyle: s.dashed ? 'dashed' : 'solid', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                                        <div className="flex items-start gap-3">
                                            <span className="px-2 py-0.5 rounded-md text-[11px] font-bold flex-shrink-0 mt-0.5 border"
                                                style={{ background: s.bg, color: s.color, borderColor: s.border }}>
                                                {action.priority}
                                            </span>
                                            <div className="flex-1 min-w-0">
                                                <p style={{ fontWeight: 600, fontSize: 14, color: '#0A0A0A', lineHeight: 1.3 }}>{action.action}</p>
                                                <p style={{ fontSize: 13, color: '#6B7280', marginTop: 4, lineHeight: 1.5 }}>{action.impact}</p>
                                            </div>
                                            <span style={{ fontSize: 13, fontWeight: 700, color: '#16A34A', flexShrink: 0, fontFamily: 'Inter, sans-serif' }}>
                                                ↓{action.scoreImprovement}pts
                                            </span>
                                        </div>
                                    </motion.div>
                                );
                            })}
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
